Locales['en'] = {
    -- Svlačionica
    ['cloakroom'] = 'Svlačionica | 👒',
    ['citizen_wear'] = 'Civilno Odelo | 👨',
    ['mafia_wear'] = 'Mafijaška Uniforma | 🎩',
    ['no_outfit'] = 'Ne postoji uniforma koja vam odgovara!',
    ['open_cloackroom'] = 'pritisnite ~INPUT_CONTEXT~ da promenite odeću.',
    -- Oružarnica
    ['remove_object'] = 'Uzmi predmet | 📷',
    ['deposit_object'] = 'Ostavi predmet| 📷',
    ['get_weapon'] = 'Uzmi oružje | 🔫',
    ['put_weapon'] = 'Ostavi oružje | 🔫',
    ['buy_weapons'] = 'Kupi oružje | 💵',
    ['armory'] = 'Oružarnica',
    ['open_armory'] = 'Pritisnite <span>E</span> da pristupite <span>oružarnici</span>.',
    ['armory_owned'] = 'Već Imate ✅',
    ['armory_free'] = 'Besplatno',
    ['armory_item'] = '%s€',
    ['armory_weapontitle'] = 'Oružarnica | ⚙️ ➥ Kupi oružje',
    ['armory_componenttitle'] = 'Dodaci za oružje | ⚙️',
    ['armory_bought'] = 'kupili ste %s za %s€',
    ['armory_money'] = 'nemate dovoljno novca za ovo oruzje',
    ['armory_hascomponent'] = 'vec imate taj dodatak!',
    ['get_weapon_menu'] = 'Oružarnica | ⚙️ ➥ Uzmi oružje',
    ['put_weapon_menu'] = 'Oružarnica | ⚙️ ➥ Ostavi oružje',
    -- Garaža
    ['vehicle_menu'] = 'vozilo',
    ['vehicle_blocked'] = 'Spawn pointi su blokirani!',
    ['garage_prompt'] = 'Pritisnite <span>E</span> da izaberete <span>vozilo</span>.',
    ['garage_title'] = 'Izaberi Vozilo | 🚗',
    ['garage_stored'] = 'Parkirano ✅',
    ['garage_notstored'] = 'Van Garaže ❌',
    ['garage_storing'] = 'Pokušavamo da uklonimo vozilo, budite sigurni da nema igrača oko njega.',
    ['garage_has_stored'] = 'Vozilo je parkirano u garazu',
    ['garage_has_notstored'] = 'U blizini nema vozila',
    ['garage_notavailable'] = 'Vaše vozilo nije parkirano.',
    ['garage_blocked'] = 'Nema slobodnih spawn pointa!',
    ['garage_empty'] = 'Nemate vozilo u garazi.',
    ['garage_released'] = 'Vaše vozilo je izparkirano iz garaze.',
    ['garage_store_nearby'] = 'u blizini nema vozila.',
    ['garage_storeditem'] = 'Izaberite Vozilo | 🚗',
    ['garage_storeitem'] = 'Parkirajte Vozilo | 🚗',
    ['garage_buyitem'] = 'Kupite Vozilo | 🚗',
    ['helicopter_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da pristupiš radnjama sa helikopterom.',
    ['helicopter_notauthorized'] = 'niste ovlašćeni da kupite helikopter.',
    ['shop_item'] = '%s€',
    ['vehicleshop_title'] = 'Kupite Vozilo | 🚗',
    ['vehicleshop_confirm'] = 'Da li želite da kupite ovo vozilo?',
    ['vehicleshop_bought'] = 'kupili ste %s za $%s',
    ['vehicleshop_money'] = 'Nemate dovoljno novca',
    ['vehicleshop_awaiting_model'] = 'vozilo se trenutno PREUZIMA & OČITAVA molimo vas sacekajte',
    ['confirm_no'] = 'Ne ❌',
    ['confirm_yes'] = 'Da ✅',
    -- Servis
    ['service_max'] = 'ne možete da uđete u službu, maksimalan službenik je u službi: %s/%s',
    ['service_not'] = 'niste ušli u službu! Morate se prvo promeniti.',
    ['service_anonunce'] = 'Informacije o sluzbi',
    ['service_in'] = 'usli ste u sluzbu dobrodosli!',
    ['service_in_announce'] = 'operator %s je usao u sluzbu!',
    ['service_out'] = 'napustili ste sluzbu.',
    ['service_out_announce'] = 'operator %s je napustio sluzbu.',
    -- Radnje
    ['citizen_interaction'] = 'Upravljaj sa ljudima',
    ['vehicle_interaction'] = 'Upravljaj sa vozilom | 🚗',
    ['object_spawner'] = 'Stvaraj Predmete | 👜',
  
    ['id_card'] = 'Licna karta | 💳',
    ['search'] = 'Pretraži',
    ['handcuff'] = 'Zaveži / Odveži',
    ['drag'] = 'Vuci',
    ['put_in_vehicle'] = 'Stavi u vozilo',
    ['out_the_vehicle'] = 'Izvuci iz vozila',
    ['no_players_nearby'] = 'nema igraca u blizini!',
    ['being_searched'] = 'Pretraženi ste od strane mafije',
    -- Vehicle interaction
    ['vehicle_info'] = 'Informacije o vozilu | 🚗',
    ['pick_lock'] = 'Obij vozilo | 🔓',
    ['vehicle_unlocked'] = 'Vozilo uspešno Otkljucano',
    ['no_vehicles_nearby'] = 'U blizini nema vozila',
    ['search_database'] = 'Pretraga po registarskom broju | 🚗',
    ['search_database_title'] = 'Informacije - pretražite registrarske brojeve',
    ['search_database_error_invalid'] = 'To nije validan registarski broj',
    ['search_database_error_not_found'] = 'ovaj registarski broj nije ni na jednom vozilu!',
    ['search_database_found'] = 'vozilo je registrovano na %s',
    -- Traffic interaction
    ['traffic_interaction'] = 'Upravljanje sa Saobraćajem | 🚦',
    ['cone'] = 'Čunj | 🛑',
    ['barrier'] = 'Granica | 🚧',
    ['spikestrips'] = 'Bodlje | ⛏️',
    ['box'] = 'Kutija | 📦',
    ['cash'] = 'Novac | 💵',
    -- ID Card Menu
    ['name'] = 'Ime: %s',
    ['job'] = 'Posao: %s',
    ['sex'] = 'Pol: %s',
    ['dob'] = 'DOB: %s',
    ['height'] = 'Visina: %s',
    ['id'] = 'Indetifikacija: %s',
    ['bac'] = 'BAC: %s',
    ['unknown'] = 'nepoznato',
    ['male'] = 'Musko',
    ['female'] = 'Zensko',
    -- Body Search Menu
    ['guns_label'] = '--- Oružja ---',
    ['inventory_label'] = '--- Inventar ---',
    ['license_label'] = ' --- Dozvole ---',
    ['confiscate'] = 'oduzmi %s',
    ['confiscate_weapon'] = 'oduzmi %s sa %s metkovima',
    ['confiscate_inv'] = 'oduzmi %sx %s',
    ['confiscate_dirty'] = 'oduzmi prljav novac: <span style="color:red;">%s€</span>',
    ['you_confiscated'] = 'Oduzeli ste %sx %s od %s',
    ['got_confiscated'] = '%sx %s Oduzeto od strane %s',
    ['you_confiscated_account'] = 'oduzeli ste %s€ (%s) od %s',
    ['got_confiscated_account'] = '%s€ (%s) oduzeo od %s',
    ['you_confiscated_weapon'] = 'oduzeli ste %s  %s  %s ',
    ['got_confiscated_weapon'] = 'Oduzeo vam je %s  %s oduzeto od strane %s',
    ['traffic_offense'] = 'Saobracajni prekrsaj | 🚦',
    ['minor_offense'] = 'Suprostavljanje policiji | 😈',
    ['average_offense'] = 'Prosečan Prekrsaj | 😠',
    ['major_offense'] = 'Veći prekršaj | 😡',
    ['fine_total'] = 'Kazna ➥ %s',
    -- Vehicle Info Menu
    ['plate'] = 'Tablice ➥ %s',
    ['owner_unknown'] = 'Vlasnik ➥ Nepoznat',
    ['owner'] = 'Vlasnik ➥ %s',
    -- Boss Menu
    ['open_bossmenu'] = 'Pritisnite <span>E</span> da otvorite <span>boss meni</span>.',
    ['quantity_invalid'] = 'nevazeća kolicina',
    ['have_withdrawn'] = 'podigli ste %sx %s',
    ['have_deposited'] = 'ostavili ste %sx %s',
    ['quantity'] = 'kolicina',
    ['inventory'] = 'inventar',
    ['mafia_stock'] = 'Mafijaške zalihe',
    -- Misc
    ['remove_prop'] = 'Pritisnite ~INPUT_CONTEXT~ da obrišete objekat.',
    ['map_blip'] = 'Mafija',
    ['unrestrained_timer'] = 'lisice vam se polako opuštajo i spadaju sa ruku.',
    ['valid_this_purchase'] = 'Da li zelite ovo odelo?',
    ['yes'] = 'Da',
    ['no'] = 'Ne',
    ['name_outfit'] = 'Ime odela',
    ['not_enough_money'] = 'Nemate dovoljno novca',
    ['press_menu'] = 'Pritisni ~INPUT_CONTEXT~ da se presvuces',
    ['clothes'] = 'Butik',
    ['you_paid'] = 'Ti si platio ',
    ['save_in_dressing'] = 'Da li zelite da nazovete vase odelo',
    ['shop_clothes'] = 'Butik',
    ['player_clothes'] = 'Promenite odecu',
    ['shop_main_menu'] = 'Svlacionica',
    ['saved_outfit'] = 'Vase odelo je sacuvano.',
    ['loaded_outfit'] = 'Presvukli ste se.',
    ['suppr_cloth'] = 'Izbrisite odelo iz svlacionice',
    ['supprimed_cloth'] = 'Ovo odelo je izbrisano iz svlacionice',
    ['impound'] = 'Zapleni vozilo | 🔐',
    ['impound_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da prekinite zaplenu',
    ['impound_canceled'] = 'prekinuli ste zaplenu',
    ['impound_canceled_moved'] = 'Zaplena nije moguća jer se vozilo u pokretu',
    ['impound_successful'] = 'zaplenili ste vozilo',
    -- Notifications - Telefon od policije (ovo ne treba)
    --['alert_mafia'] = 'Mafijaško upozorenje',
    --['phone_mafia'] = 'Mafija',
  }
  